### PR TITLE
Fixed corners issue

### PR DESCRIPTION
**Pull request by n-droidev**
Changed build.gradle version code to 2

### CODE REVIEW

**Review by ibrahimsn98 — COMMENTED** [review]
Hi,
What is the purpose of this commit?

**Comment by n-droidev** [comment]
Hi.. Corner selection for cornerRadius doesnt work.. This will fix it..  Monday, 31 January 2022, 10:22AM +04:00 from İbrahim Süren  ***@***.*** :

***@***.*** commented on this pull request.

**Comment by ibrahimsn98** [comment]
> 

It looks ok, however why all of the files looks changed?

**Comment by n-droidev** [comment]
Maybe becuase of gradle build.. There is not much changes.. You can view them Monday, 31 January 2022, 11:09AM +04:00 from İbrahim Süren  ***@***.*** :

**Comment by brookmg** [comment]
Hey @ibrahimsn98 I think you just need to release a new version for this lib. This PR isn't necessary.

**Comment by ibrahimsn98** [comment]
Hey thank you @brookmg I'm just releasing.
@n-droidev If you reopen this PR with only changed files I can check. Currently, It shows all of the library code has been changed by you. Please check "Files Changed" section.

**Comment by n-droidev** [comment]
Lutfen son versiyona tag ekle ve paylaş.. Eger ise yaramazsa yeniden pull request yaratirim.. Tesekkurler
Monday, 31 January 2022, 11:46AM +04:00 from İbrahim Süren  ***@***.*** :

>Hey thank you  @brookmg I'm just releasing.
***@***.*** If you reopen this PR with only changed files I can check. Currently, It shows all of the library code has been changed by you. Please check "Files Changed" section.

**Comment by brookmg** [comment]
Check out version 1.7.9 now @n-droidev

**Pull request closed without merging**
