### PR TITLE
Improve accessibility 

### PR DESCRIPTION
**Pull request by FannyDemey**
Hi 
I worked on making this Menu accessible with Talkback.

- First adding some contentDescription used by talkback to read menu label (if no contentDescription then it will use title attribute)
- Adding AccessibleExploreByTouchHelper to tackle touch interaction and match corresponding menuItem to add accessibility informations
- Some change to SmoothBottomBar implementation to listen to touch / hover event, and match corresponding accessible event.

I remain at your disposable for any question and will be happy to discuss with you if you have any suggestion of improvement. 

Fanny

### CODE REVIEW

**Review by ibrahimsn98 — APPROVED** [review]

**Comment by ibrahimsn98** [comment]
I have merged this request, but idk why it still shown as not merged. I'm closing this. Thank you for your contribution :)

**Comment by ibrahimsn98** [comment]
I will try to fix.

**Comment by ibrahimsn98** [comment]
@FannyDemey Can you open the same PR again?

**Comment by FannyDemey** [comment]
@ibrahimsn98  sure ! just done it. It's weird it seems some of my commits have been committed... 
Let me know if everything is ok and when you will generate a new version with that change so I can used it directly in my app.
👋

**Pull request closed without merging**
